apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictedCapabilities
metadata:
  name: restrict-capabilities
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    restrictedCaps:
      - NET_ADMIN
      - SYS_TIME

