apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sResourceLimit
metadata:
  name: required-resource-limit
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: ["kube-system", "gatekeeper-system", "kube-node-lease", "kube-public"] 
